### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by ihtishamaliktk** [ojwoodford/ibr_toolbox#1]
The mex compilation issues an error due to syntax. I am using Matlab 2018a. What is the nature of the second argument-

Error using nargin
You can only call nargin/nargout from within a MATLAB function.

Error in vgg_mexcompile_script (line 20)
if nargin == 2 && isequal(varargin{1}, 'compile')

**Comment by ojwoodford** [comment]
Thanks for reporting this. I've pushed a change which should fix this. If you get any compile errors, please let me know what platform you're using (OS, compiler). Thanks.
