### ISSUE TITLE
compilation error  (2)

### ISSUE THREAD

**Issue by ihtishamaliktk** [ojwoodford/ibr_toolbox#2]
Hi again, 
The changes you committed worked fine for first compilation. It runs fine for quite a number of iterations  until it crashes at issue 2. There are two problems, the first is a trivial fix  
(1) In Ibr_fuse_depths.m , _values.show_output_  is used as a condition for If statement. It causes an error since its a figure handle. 

(2) a compilation error arises I think in the new commit
Error in vgg_segment_gb (line 32)
[varargout{1:nargout}] = compile(varargin{:}); % Compilation happens here

I am using Microsoft Visual C++ 2017  with Matlab 2018a on windows.

**Comment by ojwoodford** [comment]
Thanks. Regarding (2), please can you paste the compilation error here, as I don't have that environment.

**Comment by ihtishamaliktk** [comment]
I guess the mex isn't searching in the right directory apparently. Its missing the vgg folder in the address.

ojw_mexcompile(funcName, sourceList)
mex -D_MATLAB_=904 -O -DNDEBUG COMPFLAGS=" $COMPFLAGS" -Iseg_gb/ "vgg_segment_gb.cxx" -output "vgg_segment_gb"
ERROR while compiling vgg_segment_gb
Error using mex
D:\codes\MVS\ibr_toolbox-master\vgg_segment_gb.cxx not found; check that you are in the correct current folder, and check the spelling of 'D:\codes\MVS\ibr_toolbox-master\vgg_segment_gb.cxx'.
ans =

    -1

**Comment by ojwoodford** [comment]
I can't reproduce the bug. If you put a breakpoint on line 46 of compile.m and run the code, what is the value of funcPath when the breakpoint is hit?

**Comment by ihtishamaliktk** [comment]
For some reason  the path  seems to be fine now. 
funcPath =  'D:\codes\MVS\ibr_toolbox-master\vgg'
currDir = 'D:\codes\MVS\ibr_toolbox-master\vgg\cones\cones'


However, the error is now visible with a bunch of warnings


Missing mex file: vgg_segment_gb.mexw64. Will attempt to compile and run.
mex -D_MATLAB_=904 -O -DNDEBUG COMPFLAGS=" $COMPFLAGS" -Iseg_gb/ "vgg_segment_gb.cxx" -output "vgg_segment_gb"
Building with 'Microsoft Visual C++ 2017'.
ERROR while compiling vgg_segment_gb
**Error using mex
vgg_segment_gb.cxx
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\include\stdint.h(17): error C2371: 'int8_t': redefinition; different basic types**
**D:\codes\MVS\ibr_toolbox-master\vgg\vgg_segment_gb.cxx(9): note: see declaration of 'int8_t'**
d:\codes\mvs\ibr_toolbox-master\vgg\seg_gb\convolve.h(34): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
d:\codes\mvs\ibr_toolbox-master\vgg\seg_gb\convolve.h(54): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
d:\codes\mvs\ibr_toolbox-master\vgg\seg_gb\imconv.h(84): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
d:\codes\mvs\ibr_toolbox-master\vgg\seg_gb\filter.h(35): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
d:\codes\mvs\ibr_toolbox-master\vgg\seg_gb\filter.h(58): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
D:\codes\MVS\ibr_toolbox-master\vgg\vgg_segment_gb.cxx(28): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
D:\codes\MVS\ibr_toolbox-master\vgg\vgg_segment_gb.cxx(39): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
D:\codes\MVS\ibr_toolbox-master\vgg\vgg_segment_gb.cxx(43): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
D:\codes\MVS\ibr_toolbox-master\vgg\vgg_segment_gb.cxx(64): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of dataK>>

**Comment by ojwoodford** [comment]
Thanks. That's a simple fix. MSVC now defines standard integer types in stdint.h, like everyone else. I've updated the code. Try latest master.
